# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84b23f653dae541d1ca1d13114cf5a59df510b580b21bd5ed15c14f80933c0d54fd91fc867bde2686a4b64b9d94c6b16488e6f4ee508fd0dba9897ed9cd43f89

test:
  secret_key_base: 32d37d0eefc0a5e131a923a8b24d1d3351ed359f7e5c322d1d629513065263afd5c4bac74a3c93ce525c7a21eba263260ba82ff63d2a5fba1318dee91eaec85f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
